version: '3.1'
services:
    app:
        build: .
        ports:
            - "${APP_PORT}:${APP_PORT}"
        depends_on:
            -   mysqldb

    mysqldb:
        image: "mysql:5.7.32"
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - "${DATABASE_PORT}:3306"
        environment:
            - "MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASS}"
            - "MYSQL_USER=${DATABASE_USER}"
            - "MYSQL_PASSWORD=${DATABASE_PASS}"
            - "MYSQL_DATABASE=${DATABASE_NAME}"
            - DATABASE_HOST=mysqldb
        
    migrate:
        image: migrate/migrate
        restart: on-failure
        volumes:
            - ./migrations:/migrations
        command: [ "-path", "/migrations", "-database",
                   "mysql://root:${DATABASE_ROOT_PASS}@tcp(${DATABASE_HOST})/${DATABASE_NAME}", "up", "4" ]
        depends_on:
            - mysqldb
            - app