CREATE TABLE IF NOT EXISTS `hgtest`.`cat_breed` (
  `id` VARCHAR(255) NOT NULL,
  `adaptability` INT(1) NOT NULL,
  `affection_level` INT(1) NOT NULL,
  `alt_names` VARCHAR(255) NOT NULL,
  `cfa_url` VARCHAR(255) NOT NULL,
  `child_friendly` INT(1) NOT NULL,
  `country_code` VARCHAR(255) NOT NULL,
  `country_codes` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `dog_friendly` INT(1) NOT NULL,
  `energy_level` INT(1) NOT NULL,
  `experimental` INT(1) NOT NULL,
  `grooming` INT(1) NOT NULL,
  `hairless` INT(1) NOT NULL,
  `health_issues` INT(1) NOT NULL,
  `hypoallergenic` INT(1) NOT NULL,
  `indoor` INT(1) NOT NULL,
  `intelligence` INT(1) NOT NULL,
  `lap` INT(1) NOT NULL,
  `life_span` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `natural` INT(1) NOT NULL,
  `origin` VARCHAR(255) NOT NULL,
  `rare` INT(1) NOT NULL,
  `reference_image_id` VARCHAR(255) NOT NULL,
  `rex` INT(1) NOT NULL,
  `shedding_level` INT(1) NOT NULL,
  `short_legs` INT(1) NOT NULL,
  `social_needs` INT(1) NOT NULL,
  `stranger_friendly` INT(1) NOT NULL,
  `supressed_tail` INT(1) NOT NULL,
  `temperament` VARCHAR(255) NOT NULL,
  `vcahospitals_url` VARCHAR(255) NOT NULL,
  `vetstreet_url` VARCHAR(255) NOT NULL,
  `vocalisation` INT(1) NOT NULL,
  `wikipedia_url` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
